// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExampleCreateCarRequestBody example create car request body
//
// swagger:model example.CreateCarRequestBody
type ExampleCreateCarRequestBody struct {

	// car type
	// Required: true
	CarType *int64 `json:"carType"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this example create car request body
func (m *ExampleCreateCarRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCarType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExampleCreateCarRequestBody) validateCarType(formats strfmt.Registry) error {

	if err := validate.Required("carType", "body", m.CarType); err != nil {
		return err
	}

	return nil
}

func (m *ExampleCreateCarRequestBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this example create car request body based on context it is used
func (m *ExampleCreateCarRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExampleCreateCarRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExampleCreateCarRequestBody) UnmarshalBinary(b []byte) error {
	var res ExampleCreateCarRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
