// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExampleErrorResp example error resp
//
// swagger:model example.ErrorResp
type ExampleErrorResp struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this example error resp
func (m *ExampleErrorResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this example error resp based on context it is used
func (m *ExampleErrorResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExampleErrorResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExampleErrorResp) UnmarshalBinary(b []byte) error {
	var res ExampleErrorResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
