// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelTExample model t example
//
// swagger:model model.TExample
type ModelTExample struct {

	// car type
	CarType int64 `json:"car_type,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`
}

// Validate validates this model t example
func (m *ModelTExample) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model t example based on context it is used
func (m *ModelTExample) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelTExample) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelTExample) UnmarshalBinary(b []byte) error {
	var res ModelTExample
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
