/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from "restful-react";
export const SPEC_VERSION = "1.0"; 
export interface ExampleCreateCarRequestBody {
  carType: number;
  name: string;
}

export interface ExampleErrorResp {
  msg?: string;
}

export interface ModelTExample {
  car_type?: number;
  id?: number;
  /**
   * Name
   */
  name?: string;
}

export type ListCarProps = Omit<GetProps<ModelTExample[], unknown, void, void>, "path">;

/**
 * ListCar
 * 
 * List car
 */
export const ListCar = (props: ListCarProps) => (
  <Get<ModelTExample[], unknown, void, void>
    path={`/car`}
    
    {...props}
  />
);

export type UseListCarProps = Omit<UseGetProps<ModelTExample[], unknown, void, void>, "path">;

/**
 * ListCar
 * 
 * List car
 */
export const useListCar = (props: UseListCarProps) => useGet<ModelTExample[], unknown, void, void>(`/car`, props);


export type CreateCarProps = Omit<MutateProps<ModelTExample, ExampleErrorResp, void, ExampleCreateCarRequestBody, void>, "path" | "verb">;

/**
 * CreateCar
 * 
 * Create Car
 */
export const CreateCar = (props: CreateCarProps) => (
  <Mutate<ModelTExample, ExampleErrorResp, void, ExampleCreateCarRequestBody, void>
    verb="POST"
    path={`/car`}
    
    {...props}
  />
);

export type UseCreateCarProps = Omit<UseMutateProps<ModelTExample, ExampleErrorResp, void, ExampleCreateCarRequestBody, void>, "path" | "verb">;

/**
 * CreateCar
 * 
 * Create Car
 */
export const useCreateCar = (props: UseCreateCarProps) => useMutate<ModelTExample, ExampleErrorResp, void, ExampleCreateCarRequestBody, void>("POST", `/car`, props);

