// Code generated by go-swagger; DO NOT EDIT.

package ex

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"kunlun-qilian/server-example/cmd/client/models"
)

// NewCreateCarParams creates a new CreateCarParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCarParams() *CreateCarParams {
	return &CreateCarParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCarParamsWithTimeout creates a new CreateCarParams object
// with the ability to set a timeout on a request.
func NewCreateCarParamsWithTimeout(timeout time.Duration) *CreateCarParams {
	return &CreateCarParams{
		timeout: timeout,
	}
}

// NewCreateCarParamsWithContext creates a new CreateCarParams object
// with the ability to set a context for a request.
func NewCreateCarParamsWithContext(ctx context.Context) *CreateCarParams {
	return &CreateCarParams{
		Context: ctx,
	}
}

// NewCreateCarParamsWithHTTPClient creates a new CreateCarParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCarParamsWithHTTPClient(client *http.Client) *CreateCarParams {
	return &CreateCarParams{
		HTTPClient: client,
	}
}

/* CreateCarParams contains all the parameters to send to the API endpoint
   for the create car operation.

   Typically these are written to a http.Request.
*/
type CreateCarParams struct {

	/* ReqeustBody.

	   Create Car
	*/
	ReqeustBody *models.ExampleCreateCarRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create car params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCarParams) WithDefaults() *CreateCarParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create car params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCarParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create car params
func (o *CreateCarParams) WithTimeout(timeout time.Duration) *CreateCarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create car params
func (o *CreateCarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create car params
func (o *CreateCarParams) WithContext(ctx context.Context) *CreateCarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create car params
func (o *CreateCarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create car params
func (o *CreateCarParams) WithHTTPClient(client *http.Client) *CreateCarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create car params
func (o *CreateCarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReqeustBody adds the reqeustBody to the create car params
func (o *CreateCarParams) WithReqeustBody(reqeustBody *models.ExampleCreateCarRequestBody) *CreateCarParams {
	o.SetReqeustBody(reqeustBody)
	return o
}

// SetReqeustBody adds the reqeustBody to the create car params
func (o *CreateCarParams) SetReqeustBody(reqeustBody *models.ExampleCreateCarRequestBody) {
	o.ReqeustBody = reqeustBody
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ReqeustBody != nil {
		if err := r.SetBodyParam(o.ReqeustBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
