// Code generated by go-swagger; DO NOT EDIT.

package ex

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"KunLunQiLian/server-example/cmd/client/models"
)

// CreateCarReader is a Reader for the CreateCar structure.
type CreateCarReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCarReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCarOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCarBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCarInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCarOK creates a CreateCarOK with default headers values
func NewCreateCarOK() *CreateCarOK {
	return &CreateCarOK{}
}

/* CreateCarOK describes a response with status code 200, with default header values.

OK
*/
type CreateCarOK struct {
	Payload *models.ModelTExample
}

func (o *CreateCarOK) Error() string {
	return fmt.Sprintf("[POST /car][%d] createCarOK  %+v", 200, o.Payload)
}
func (o *CreateCarOK) GetPayload() *models.ModelTExample {
	return o.Payload
}

func (o *CreateCarOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelTExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCarBadRequest creates a CreateCarBadRequest with default headers values
func NewCreateCarBadRequest() *CreateCarBadRequest {
	return &CreateCarBadRequest{}
}

/* CreateCarBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateCarBadRequest struct {
	Payload *models.ExampleErrorResp
}

func (o *CreateCarBadRequest) Error() string {
	return fmt.Sprintf("[POST /car][%d] createCarBadRequest  %+v", 400, o.Payload)
}
func (o *CreateCarBadRequest) GetPayload() *models.ExampleErrorResp {
	return o.Payload
}

func (o *CreateCarBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExampleErrorResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCarInternalServerError creates a CreateCarInternalServerError with default headers values
func NewCreateCarInternalServerError() *CreateCarInternalServerError {
	return &CreateCarInternalServerError{}
}

/* CreateCarInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateCarInternalServerError struct {
	Payload *models.ExampleErrorResp
}

func (o *CreateCarInternalServerError) Error() string {
	return fmt.Sprintf("[POST /car][%d] createCarInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateCarInternalServerError) GetPayload() *models.ExampleErrorResp {
	return o.Payload
}

func (o *CreateCarInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExampleErrorResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
