EXAMPLE_SERVER__DB_DBName: example
EXAMPLE_SERVER__DB_Extra: autocommit=true&charset=utf8mb4&interpolateParams=true&loc=Local&parseTime=true
EXAMPLE_SERVER__DB_Host: 127.0.0.1
EXAMPLE_SERVER__DB_Password: "123456"
EXAMPLE_SERVER__DB_PoolSize: "10"
EXAMPLE_SERVER__DB_Port: "33306"
EXAMPLE_SERVER__DB_User: root
EXAMPLE_SERVER__Server_LogFormatter: json
EXAMPLE_SERVER__Server_LogLevel: debug
EXAMPLE_SERVER__Server_Mode: debug
EXAMPLE_SERVER__Server_Port: "80"
EXAMPLE_SERVER__TestEnvStr: global.config
GOENV: DEV
