// Package client_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/kunlun-qilian/klctl version (devel) DO NOT EDIT.
package client_server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ExampleCreateCarRequestBody defines model for example.CreateCarRequestBody.
type ExampleCreateCarRequestBody struct {
	CarType int    `json:"carType"`
	Name    string `json:"name"`
}

// ExampleErrorResp defines model for example.ErrorResp.
type ExampleErrorResp struct {
	Msg *string `json:"msg,omitempty"`
}

// ModelExample defines model for model.Example.
type ModelExample struct {
	CarType *int    `json:"CarType,omitempty"`
	Ff      *string `json:"ff,omitempty"`

	// Name Name
	Name   *string `json:"name,omitempty"`
	UserID *string `json:"userID,omitempty"`
}

// CreateCarJSONRequestBody defines body for CreateCar for application/json ContentType.
type CreateCarJSONRequestBody = ExampleCreateCarRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCar request
	ListCar(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCar request with any body
	CreateCarWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCar(ctx context.Context, body CreateCarJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCar(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCarRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCarWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCarRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCar(ctx context.Context, body CreateCarJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCarRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCarRequest generates requests for ListCar
func NewListCarRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/car")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCarRequest calls the generic CreateCar builder with application/json body
func NewCreateCarRequest(server string, body CreateCarJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCarRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCarRequestWithBody generates requests for CreateCar with any type of body
func NewCreateCarRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/car")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCar request
	ListCarWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCarResponse, error)

	// CreateCar request with any body
	CreateCarWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCarResponse, error)

	CreateCarWithResponse(ctx context.Context, body CreateCarJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCarResponse, error)
}

type ListCarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ModelExample
}

// Status returns HTTPResponse.Status
func (r ListCarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelExample
	JSON400      *ExampleErrorResp
	JSON500      *ExampleErrorResp
}

// Status returns HTTPResponse.Status
func (r CreateCarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListCarWithResponse request returning *ListCarResponse
func (c *ClientWithResponses) ListCarWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCarResponse, error) {
	rsp, err := c.ListCar(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCarResponse(rsp)
}

// CreateCarWithBodyWithResponse request with arbitrary body returning *CreateCarResponse
func (c *ClientWithResponses) CreateCarWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCarResponse, error) {
	rsp, err := c.CreateCarWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCarResponse(rsp)
}

func (c *ClientWithResponses) CreateCarWithResponse(ctx context.Context, body CreateCarJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCarResponse, error) {
	rsp, err := c.CreateCar(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCarResponse(rsp)
}

// ParseListCarResponse parses an HTTP response from a ListCarWithResponse call
func ParseListCarResponse(rsp *http.Response) (*ListCarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ModelExample
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateCarResponse parses an HTTP response from a CreateCarWithResponse call
func ParseCreateCarResponse(rsp *http.Response) (*CreateCarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelExample
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ExampleErrorResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ExampleErrorResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUT2/bPgz9KgZ/v6Njpd12yWltlkOwoi2a3oYeVJmxVdiSStFJg8LffZBsN8liFB02",
	"7GRZJB//Pb1XULZ21qBhD7NX8KrEWsYjvsjaVZjNCSXjXNIdPjfo+dLmu2B3ZB0Sa4zeStL9zmE4cvyC",
	"NowFErQpGFkfWjyTNgW0bQqEz40mzGH24w2i939IB3/7+ISKA9BQ04LI0h16d1pI7YvxVCdgtc2xyhYd",
	"5CnQ/L2O1uuRJPtGc/SKtGNtDczgOtymp96NR1p++1C14UqbtY2jtoal4rijWuoqBDbOWeKvfiuLAinT",
	"dpjiDC5ul8mqs0MKDQX/ktnNhNhut9k+RPQoobTjBu5L7RPtE5n4OKzEI22Qkltkz5aG/wxSqLRC4+MQ",
	"hvxOqhKT82w6ll5Ga2apEH2oF1fL+eJ6tZicZ9Os5LoKBTFS7W/WK6SNVrjHOCg/uogwaM1hobDqbEm/",
	"4uTidgkpbJB819ZZNg3Q1qGRTsMMPmXT7AxScJLLyAGhJIVvgXy61ivtOQkOEYJkuF7mvWEe7wm9s6Gn",
	"EH0+nQ7rQxPxpHOVVjFQPPkAOrzAcNKMdQz8n3ANM/hP7N+q6B+qOCbxnjiSSO463hxXffM98ss3dS1p",
	"d1Qty8KHh4gv8NCm4Kwf6bqTg2Q+0vebUkD3sA/E4sNNv9fru4o00upRqXulYWqw/cPd/MZKxleQwue/",
	"mPJUF0fSXso86ScW8n/51/mXhpGMrJJVpx7R+RcyHlLokI4pvEyUzbFAM+mpNXm0+W7Si8wdPmNzyIRO",
	"kUL8ay86QlRWyaq0noV0WmzOoH1ofwYAAP//Ke2MbwEHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
