EXAMPLE_SERVER__DB_DBName: example
EXAMPLE_SERVER__DB_Host: 127.0.0.1
EXAMPLE_SERVER__DB_Password: abc123
EXAMPLE_SERVER__DB_PoolSize: "10"
EXAMPLE_SERVER__DB_Port: "55433"
EXAMPLE_SERVER__DB_User: postgres
EXAMPLE_SERVER__Logger_Level: DEBUG
EXAMPLE_SERVER__Logger_Output: Always
EXAMPLE_SERVER__Server_Mode: debug
EXAMPLE_SERVER__Server_UseH2C: "false"
EXAMPLE_SERVER__TestEnvStr: global.config
GOENV: DEV
